### ISSUE TITLE
Video Reference Image Won't Render

### ISSUE THREAD

**Issue by sarahohashi** [DeniseCaiLab/ezTrack#71]
I've used ezTrack in the past with no difficulties, but this time when I use it and upload my videos it isn't rendering the reference videos to crop or set ROIs. Instead it just tells me the specs of the video. Ex:

total frames: 1018
nominal fps: 29.97002997002997
dimensions (h x w): 720,1280

I used the example video for location tracking on your github for that above example, so it's not a problem with the video. Any ideas what could be going on?

**Comment by sarahohashi** [comment]
For more context, I am getting this error code in terminal when it happens:

[E 19:24:50.902 NotebookApp] Uncaught exception, closing connection.
    Traceback (most recent call last):
      File "/usr/local/anaconda3/envs/ezTrack/lib/python3.8/site-packages/tornado/iostream.py", line 702, in _handle_events
        self._handle_write()
      File "/usr/local/anaconda3/envs/ezTrack/lib/python3.8/site-packages/tornado/iostream.py", line 976, in _handle_write
        self._write_buffer.advance(num_bytes)
      File "/usr/local/anaconda3/envs/ezTrack/lib/python3.8/site-packages/tornado/iostream.py", line 182, in advance
        assert 0 < size <= self._size
    AssertionError

**Comment by ZachPenn** [comment]
Often this is an issue with either the conda environment or the web browser.  I would make sure to use the latest installation instructions (https://github.com/denisecailab/ezTrack/wiki/Installation) and use Google Chrome.
